{
    "teams": {
      "everyone": {
        "description": "a team that contains all users",
        "users": [
          "markelliot"
        ]
      }
    },
    "reviewers": {
        ".github/": {
            "description": "Require markelliot's approval on all changes to .github",
            "users": ["markelliot"],
            "requiredApproverCount": 1
        },
        "": {
            "description": "Require at least one approval on every file from the everyone team",
            "users": ["delebedev", "pturovsk"],
            "requiredApproverCount": 1
        }
    }
}