name: 'mandatory-reviews'
on: 
  pull_request:
    branches: [ "main" ]
jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Mandatory reviews
        uses: ankeetmaini/mandatory-reviews@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          usernames: delebedev,pturovsk
  test-2:
    name: Required Reviews
    runs-on: ubuntu-latest
    steps:
      - name: required-reviewers
        uses: theoremlp/required-reviews@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}